# Production Code - Testing or Deployment Code
### * Note each step is required to test a single record i.e. encoing etc

In [27]:
test=[3, "male", 22.0, 1, 0, 7.25, "S", "Third"]

In [40]:
sexle=pkl.load(open("sex_encoder.pkl","rb"))
embarkle=pkl.load(open("embark_encoder.pkl","rb"))
classle=pkl.load(open("class_encoder.pkl","rb"))
model = pkl.load(open("classifier.pkl", "rb"))

In [31]:
test[1]

'male'

In [33]:
sexle.classes_

array(['female', 'male'], dtype=object)

In [36]:
sexle.transform(test[1])

ValueError: y should be a 1d array, got an array of shape () instead.

In [42]:
sexle.transform([test[1]])

array([1])

In [50]:
print(sexle.transform([test[1]])[0])
test[1] = sexle.transform([test[1]])[0]

1


In [51]:
print(embarkle.transform([test[6]])[0])
test[6] = embarkle.transform([test[6]])[0]

2


In [52]:
print(classle.transform([test[7]])[0])
test[7] = classle.transform([test[7]])[0]

2


In [53]:
model.predict(test)

ValueError: Expected 2D array, got 1D array instead:
array=[ 3.    1.   22.    1.    0.    7.25  2.    2.  ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [54]:
model.predict([test])

array([1], dtype=int64)

In [55]:
y[0]

0

In [60]:
import numpy as np
np.array(test).reshape(1,8)

array([[ 3.  ,  1.  , 22.  ,  1.  ,  0.  ,  7.25,  2.  ,  2.  ]])

In [61]:
np.array(test).reshape(8,1)

array([[ 3.  ],
       [ 1.  ],
       [22.  ],
       [ 1.  ],
       [ 0.  ],
       [ 7.25],
       [ 2.  ],
       [ 2.  ]])

In [59]:
model.predict(np.array(test).reshape(1,8))

array([1], dtype=int64)